# Generated by Django 3.0.3 on 2020-04-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_acquisition_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundinground',
            name='transaction_name',
            field=models.CharField(default='Sample Transaction', max_length=500),
            preserve_default=False,
        ),
    ]
