# Generated by Django 3.0.3 on 2020-04-26 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_fundinground_transaction_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='personjob',
            name='organization',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='org.Organization'),
        ),
    ]
