# Generated by Django 3.0.3 on 2020-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0006_personjob_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='markets',
            field=models.TextField(blank=True),
        ),
    ]
