# Generated by Django 3.0.3 on 2020-06-28 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_auto_20200628_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail_url',
            field=models.TextField(null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
