# Generated by Django 3.0.3 on 2020-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_auto_20200628_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
