# Generated by Django 3.0.3 on 2020-07-01 18:42

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0012_auto_20200628_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='first_name', unique=True),
        ),
    ]
