# Generated by Django 3.0.3 on 2020-07-01 18:45

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0013_person_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='acquisition',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='transaction_name', unique=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True),
        ),
    ]
