# Generated by Django 3.0.3 on 2020-07-01 18:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0014_auto_20200702_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='fundinground',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='transaction_name', unique=True),
        ),
        migrations.AddField(
            model_name='news',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='title', unique=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=200, null=True, populate_from='name', unique=True),
        ),
    ]
