# Generated by Django 3.0.3 on 2020-07-03 15:15

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0015_auto_20200702_0048'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryContentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'library_content_types',
            },
        ),
        migrations.CreateModel(
            name='LibraryContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=200, populate_from='title', unique=True)),
                ('profile_image', models.ImageField(default=None, max_length=2056, null=True, upload_to='organization')),
                ('short_description', models.TextField(null=True)),
                ('url', models.TextField(null=True, validators=[django.core.validators.URLValidator()])),
                ('date_year', models.CharField(blank=True, max_length=4)),
                ('date_month', models.CharField(blank=True, max_length=14)),
                ('date_day', models.CharField(blank=True, max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='org.LibraryContentType')),
            ],
            options={
                'db_table': 'library_contents',
            },
        ),
    ]
