# Generated by Django 3.0.3 on 2020-07-03 17:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0016_librarycontent_librarycontenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryContentPerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('library_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.LibraryContent')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.Person')),
            ],
            options={
                'db_table': 'library_content_persons',
            },
        ),
    ]
