# Generated by Django 3.0.3 on 2020-08-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0018_acquisitionlibrarycontent_eventlibrarycontent_fundinglibrarycontent_organizationlibrarycontent_perso'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarycontent',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
