# Generated by Django 3.0.3 on 2020-08-12 15:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0019_librarycontent_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBusinessSubModelType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_business_model_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.PlatformBusinessModelType')),
            ],
            options={
                'db_table': 'platform_business_sub_model_types',
            },
        ),
    ]
